"""Export the 14 canon regions as a lat/lng GeoJSON asset for the app's Atlas (Leaflet).

Reuses the already-built regions_geo.json (baked equirectangular map coords, x=lon+180,
y=90-lat) — inverting those back to lon/lat is exact — and the canon palette from build_data.
Writes an ES module the Atlas page can import directly (no new route / fetch):

    python mockups/62-facet-map/export_atlas_regions.py
"""
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import build_data as BD  # noqa: E402  (REGIONS: (name, color, trads))

COLOR = {name: color for name, color, _ in BD.REGIONS}
geo = json.loads((HERE / "regions_geo.json").read_text())

features = []
for name, d in geo.items():
    if name not in COLOR:          # skip Antarctica (not a canon region)
        continue
    polygons = []
    for ring in d.split("Z"):
        nums = re.findall(r"-?\d[\d.]*", ring)
        if len(nums) < 6:
            continue
        coords = [[round(float(nums[i]) - 180, 2), round(90 - float(nums[i + 1]), 2)]
                  for i in range(0, len(nums) - 1, 2)]
        if coords[0] != coords[-1]:
            coords.append(coords[0])   # close the ring
        polygons.append([coords])
    features.append({
        "type": "Feature",
        "properties": {"name": name, "color": COLOR[name]},
        "geometry": {"type": "MultiPolygon", "coordinates": polygons},
    })

fc = {"type": "FeatureCollection", "features": features}
dest = HERE.parents[1] / "src/server/web/assets/regions-geo.js"
dest.write_text("// generated by mockups/62-facet-map/export_atlas_regions.py — do not edit\n"
                "export const REGIONS_GEOJSON = " + json.dumps(fc, separators=(",", ":")) + ";\n",
                encoding="utf-8")
print(f"{len(features)} regions → {dest.relative_to(HERE.parents[1])} ({dest.stat().st_size / 1024:.0f}KB)")
