#!/usr/bin/env python3
"""Refresh the TMI citation-key and regenerate its human-readable doc.

The key itself is built by the pipeline (``motifs.sources.bibliography``) into
``outputs/motifs/tmi_bibliography.json`` — the same code ``mytho motifs`` runs.
This wrapper rebuilds it standalone and additionally writes the committed
``docs/motifs/tmi-bibliography-key.md`` (a documentation artifact, not build output).

Run: ``python scripts/build_tmi_bibliography.py`` (re-fetches the folkmasa page
unless already cached under ``outputs/motifs/raw/``; needs a built ``tmi.json``).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from motifs import store  # noqa: E402
from motifs.sources import bibliography  # noqa: E402

OUT_DOC = ROOT / "docs" / "motifs" / "tmi-bibliography-key.md"


def write_doc(data: dict) -> None:
    lines = [
        "# TMI bibliography key",
        "",
        "Decodes the abbreviated citations in Thompson Motif-Index `notes` into full",
        "titles and live book links. Generated by `scripts/build_tmi_bibliography.py`.",
        "",
        f"English bibliography parsed from <{data['source_url']}>; foreign works added",
        "as a curated supplement. `uses` = approximate citation count in the built TMI data.",
        "",
        "## Series & journal acronyms",
        "",
    ]
    for ab, full in sorted(data["series"].items()):
        lines.append(f"- **{ab}** — {full}")
    lines += ["", "## Works (most-cited first)", "",
              "| uses | shorthand | full citation | link |", "|---:|---|---|---|"]
    for r in data["entries"]:
        short = ", ".join(f"`{k}`" for k in r["keys"])
        link = " · ".join(f"[{u['label'] or i + 1}]({u['url']})" for i, u in enumerate(r["urls"])) or "—"
        cite = r["citation"].replace("|", "\\|")
        tag = "" if r["source"] == "folkmasa" else " ✚"
        lines.append(f"| {r['uses']} | {short}{tag} | {cite} | {link} |")
    lines += ["", "✚ = curated supplement (not in the English bibliography).", ""]
    OUT_DOC.write_text("\n".join(lines))


def main() -> int:
    tmi_path = store.index_path("tmi")
    if not tmi_path.exists():
        print("Build the motif database first (mytho motifs) — tmi.json is needed.", file=sys.stderr)
        return 1
    tmi_records = json.loads(tmi_path.read_text("utf-8"))["motifs"]
    bibliography.refresh(tmi_records, force=False)
    data = json.loads(bibliography.out_path().read_text("utf-8"))
    write_doc(data)
    print(f"{len(data['entries'])} entries -> {bibliography.out_path()}, {OUT_DOC}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
